Repository hvaandres/starving_flutter, pull requests merged in 2025-04, with the labels that each got.

#4 [BOc] Integrate isar library
  lib/data/datasource/isar_datasource.dart
  lib/domain/datasource/local_storage_datasource.dart
  lib/domain/grocery.dart
  pubspec.yaml
Labels: documentation

#6 [BOc] Add missing grocery database class
  lib/domain/entity/grocery.g.dart
Labels: bug

#7 [BOc] extension color manager
  lib/config/theme/color_manager.dart
  lib/config/theme/color_manager_extension.dart
  lib/presentation/screens/items_screen.dart
  lib/presentation/screens/main_screen.dart
  lib/presentation/screens/reminders_screen.dart
  lib/presentation/screens/settings_screen.dart
  lib/presentation/screens/today_screen.dart
  lib/shared/examples/screens/custom_card_icon_screen.dart
Labels: documentation, enhancement

#8 [BOc] create EmptyState
  lib/presentation/screens/items_screen.dart
  lib/presentation/screens/today_screen.dart
  lib/shared/examples/screens/skeleton_dynamic_container_screen.dart
  lib/shared/widget/empty_state_dynamic.dart
  lib/shared/widget/skeleton_dynamic_container.dart
  lib/shared/widget/widgets.dart
Labels: documentation, enhancement

#9 [BOc] integrate bloc, injector, freezed
  lib/code/di/injector.dart
  lib/main.dart
  lib/presentation/blocs/grocery_bloc.dart
  lib/presentation/blocs/grocery_event.dart
  lib/presentation/blocs/grocery_event.freezed.dart
  lib/presentation/blocs/grocery_state.dart
  lib/presentation/blocs/grocery_state.freezed.dart
  lib/presentation/provider/grocery_provider.dart
  lib/presentation/provider/storage/local_storage_provider.dart
  lib/presentation/screens/items_screen.dart
  pubspec.yaml
Labels: documentation, enhancement

#10 [BOc] add missing const
  analysis_options.yaml
  lib/config/theme/base_colors.dart
  lib/presentation/blocs/grocery_bloc.dart
  lib/presentation/screens/main_screen.dart
  lib/presentation/screens/settings_screen.dart
  lib/presentation/widget/items_list_middle_screen.dart
  lib/shared/examples/screens/card_options_screen.dart
  lib/shared/examples/screens/custom_asset_image_screen.dart
  lib/shared/examples/screens/custom_card_icon_screen.dart
  lib/shared/examples/screens/custom_edit_text_screen.dart
  lib/shared/examples/screens/dynamic_card_screen.dart
  lib/shared/examples/screens/examples_screen.dart
  lib/shared/examples/screens/open_url_screen.dart
  lib/shared/examples/screens/paragraph_card_screen.dart
  lib/shared/examples/screens/simple_form_bottomsheet_screen.dart
  lib/shared/examples/screens/skeleton_dynamic_container_screen.dart
  lib/shared/widget/card_options.dart
  lib/shared/widget/custom_edit_text.dart
  lib/shared/widget/dynamic_card.dart
  lib/shared/widget/paragraph_card.dart
  lib/shared/widget/skeleton_dynamic_container.dart
Labels: documentation, enhancement

#11 [BOc] Replace Isar by sqlite
  android/app/build.gradle.kts
  lib/code/di/injector.dart
  lib/data/database/grocery_database.dart
  lib/data/database/utils.dart
  lib/data/datasource/isar_datasource.dart
  lib/data/repository/local_storage_repository_impl.dart
  lib/domain/datasource/local_storage_datasource.dart
  lib/domain/entity/grocery.dart
  lib/domain/entity/grocery.g.dart
  lib/domain/repository/local_storage_repository.dart
  lib/main.dart
  lib/presentation/blocs/grocery_bloc.dart
  pubspec.yaml
Labels: documentation, enhancement
